name = "lytix-auth"
compatibility_date = "2025-04-01"
pages_build_output_dir = "public"

# D1 数据库绑定（填入 database_id 后推送即可生效）
[[d1_databases]]
binding = "DB"
database_name = "lytix-auth"
database_id = "b5ee1f00-5bf1-4cd1-88be-a7caa91203a9"
